#!/usr/bin/env python
"""Freeze 《高性价比人生指南》 (eternity4719/HowToLiveBetter) into assets/life_guide.json.

Maintenance tool, excluded from the runtime package. It reads the GitHub
codeload ZIP directly and refuses any ZIP whose embedded commit is not the
pinned one, so the frozen text cannot drift from a folder edited by hand.

What is kept, verbatim: every entry's six fields and machine cost tags, each
section's intro, all long articles under docs/, and from README the question
each section answers, the four resources, the evidence grades, the
cost-effectiveness tiers and the glossary. Computed the book's way (its
index.html): the cost score and the 极高/高/一般 tier, the 争议 badge, the
待核实 flag, and every cross reference resolved to its target (its
tools/check-refs.mjs, ported in life_guide_refs.py).

Three entries are left out on purpose, by number checked against a title
fragment, as a product-scope decision: this skill does not carry the book's
verdicts on divination. The output holds no trace of them. Everything else is
kept, so the library is the whole book minus those three, not the whole book.

Regions and reviewed dispute quotes come from life_guide_review.py, keyed by
title so a renumbering upstream cannot land a review on the wrong entry.

    python scripts/import_life_guide.py --zip path/to/howtolivebetter-main.zip
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import zipfile
from pathlib import Path

from life_guide_refs import scan
from life_guide_review import DISPUTE_SENTENCES, REGION
from utils import ensure_utf8_stdio

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'assets' / 'life_guide.json'
REPO = 'https://github.com/eternity4719/HowToLiveBetter'
COMMIT = '842e11c9d51fac7943e5abb4e332e29b460b5061'
SNAPSHOT_DATE = '2026-10-05'
LICENSE = {
    'text': 'CC BY 4.0', 'text_url': 'https://creativecommons.org/licenses/by/4.0/',
    'code': 'MIT（检索排序与引用检查的算法移植自其 index.html 与 tools/check-refs.mjs，'
            '决策流程移植自 skills/life-decision-guide；许可原文见 code_notice）',
    'attribution': '《高性价比人生指南》，eternity4719，https://github.com/eternity4719/HowToLiveBetter',
    'changes': '按提交 842e11c9 冻结并转成 JSON；按产品范围略去 3 条条目和第 6 节导读里转述它们的一段；'
               '其余条目、导读与长文的文字未改动',
}
FIELDS = ('成本', '说人话', '收益', '证据等级', '来源', '备注')

# Number → (a fragment its title must contain, why). The fragment guards
# against a renumbering silently excluding some other entry.
EXCLUDED = {
    (6, 15): ('不要花钱算命', '产品范围：本技能不收录评价占卜一类做法的条目'),
    (6, 22): ('转运', '产品范围：本技能不收录评价转运、招财物件的条目'),
    (29, 12): ('变故后的头三个月', '产品范围：备注里有一句评价占卜的话（指向第 6 节第 15 条），同样不收录'),
}
# Intro paragraphs left out for the same reason: section → (the paragraph's
# opening, why). Section 6's overview lists 6:15 and 6:22 by what they say.
EXCLUDED_PARAGRAPHS = {
    6: ('**花钱买运气和心情**', '产品范围：这一段导读按主题转述了被排除的第 15、22 条'),
}
# Words that mark an entry as passing judgement on divination. The run fails
# on any kept entry, intro or article containing one until it is reviewed.
# Not 转运: the book uses it for 医疗转运.
DIVINATION_WORDS = ('算命', '占卜', '塔罗', '星座', '风水', '招财', '开光', '命理', '玄学', '八字')

# Default region by section, then REGION (life_guide_review.py) per entry.
UNIVERSAL_SECTIONS = {2, 3, 4, 22, 28}
ABROAD_SECTIONS = {21, 32}
# Long articles under docs/: file → (id, region). 引用对照.md is generated by
# the book's tooling and 核实记录/ is history, so neither is an article.
ARTICLES = {
    '结婚划不划算.md': ('marriage', '中国大陆'),
    '家庭应急装备清单.md': ('emergency_kit', '中国大陆'),          # 应急管理部的清单
    '做平台要办哪些证.md': ('platform_licenses', '中国大陆'),
    '遇到陌生人出事该不该停.md': ('stranger_emergency', '中国大陆'),
    '生物钟和夜班.md': ('night_shift', '通用'),                    # 只引研究
    '被裁了之后先做什么.md': ('laid_off', '中国大陆'),
    '孩子出生前后要办的事.md': ('birth_paperwork', '中国大陆'),
    '刚确诊慢性病之后.md': ('chronic_diagnosis', '中国大陆'),       # 医保家庭共济
}
NOT_ARTICLES = {'引用对照.md'}
# The book's cost weights and tiers (index.html: COST_W and e.ratio).
COST_W = {'钱': {'0': 0, '少': 1, '多': 2}, '时间': {'少': 0, '中': 1, '多': 2}, '毅力': {'否': 0, '些': 1, '是': 2}}
LENS = {'死亡率': '换寿命', '金钱': '换钱', '时间': '换时间精力', '自由': '换人身自由'}
# Kept entries (by title), intros ('节首:N') or articles ('长文:id') that refer
# to an excluded entry, once reviewed. The run fails on any new one.
REVIEWED_CROSS_REFS: dict[tuple[str, tuple[int, int]], str] = {
    ('节首:29', (29, 12)): '导读只按主题提到「不可逆的大决定往后推」，不含评价占卜的话；本库没有这一条，引用不解析',
    ('长文:laid_off', (29, 12)): '长文按主题写「头三个月里，不可逆的大决定往后推」，不含评价占卜的话；引用不解析',
}
# A reference to a whole section holding an excluded entry (「第 6 节」), once
# reviewed: (source, section) → resolution.
REVIEWED_SECTION_REFS: dict[tuple[str, int], str] = {
    ('别为了试偏方、保健品停掉正规治疗', 6): '指向第 6 节里偏方、补充剂一类的无效花费，不是被排除的两条',
    ('不要指望买东西改善心情或身份感', 29): '指向第 29 节里情绪低落时的做法，不是被排除的第 12 条',
    ('12 到 18 岁的孩子做一次抑郁筛查，别拿学校的心理测评当诊断', 29): '指向第 29 节里家人的应对，不是被排除的第 12 条',
    ('不买号称能「治愈近视」「降低度数」的产品和服务', 6): '指向第 6 节的防蓝光眼镜一条，不是被排除的两条',
    ('节首:30', 29): '指向第 29 节里家长去世后的孩子，不是被排除的第 12 条',
}

ENTRY_RE = re.compile(r'^### (\d+)\. (.+)$', re.M)
SECTION_RE = re.compile(r'^#{1,2} (\d+)\. (.+)$', re.M)
TAG_RE = re.compile(r'<!--\s*成本标签:\s*(.*?)\s*-->')
# The book marks a dispute by opening the 备注 with it (index.html: /^争议/).
# The quote is the sentence the mark opens, the next one when the mark is a
# short label (「争议。」), and as many as DISPUTE_SENTENCES says for a lead-in.
DISPUTE_RE = re.compile(r'^\s*(争议[^。！？]*[。！？]?)')
SECTION_ONLY_RE = re.compile(r'第\s*(\d+)\s*节(?!\s*第)')
QUOTE_RE = re.compile(r'「([^」]{4,60})」')
NAV_RE = re.compile(r'^\[←.*\]\(.*\)\s*$')


def ratio(tags: dict[str, str]) -> tuple[int, str]:
    """The book's cost score (钱 + 时间 + 毅力) and 性价比 tier."""
    score = sum(COST_W[k].get(tags.get(k, ''), 0) for k in COST_W)
    level = tags.get('收益')
    if level == '大':
        tier = '极高' if score == 0 else ('高' if score <= 2 else '一般')
    elif level == '中':
        tier = '高' if score == 0 else '一般'
    else:
        tier = '一般'
    return score, tier


def _region(section: int, title: str) -> str:
    if title in REGION:
        return REGION[title]
    if section in ABROAD_SECTIONS:
        return '中国公民在境外'
    return '通用' if section in UNIVERSAL_SECTIONS else '中国大陆'


def _dispute(note: str, sentences: int = 1) -> str | None:
    found = DISPUTE_RE.match(note)
    if not found:
        return None
    text = found.group(1).strip()
    rest = note[found.end():]
    wanted = sentences + (1 if len(text) <= 10 else 0)
    for _ in range(wanted - 1):
        following = re.match(r'\s*([^。！？]+[。！？]?)', rest)
        if not following:
            break
        text += following.group(1).strip()
        rest = rest[following.end():]
    return text


def _entry(section: int, section_title: str, block: str) -> dict:
    head = ENTRY_RE.match(block)
    if not head:
        raise ValueError(f'第 {section} 节有无法识别的条目标题：{block[:40]!r}')
    number, title = int(head.group(1)), head.group(2).strip()
    fields = {}
    for name in FIELDS:
        found = re.search(rf'^- {name}：(.*)$', block, re.M)
        if not found or not found.group(1).strip():
            raise ValueError(f'第 {section} 节第 {number} 条缺「{name}」栏')
        fields[name] = found.group(1).strip()
    tags = TAG_RE.search(block)
    if not tags:
        raise ValueError(f'第 {section} 节第 {number} 条缺成本标签')
    cost_tags = dict(pair.split('=', 1) for pair in tags.group(1).split())
    grade = fields['证据等级'][:1]
    if grade not in 'ABC':
        raise ValueError(f'第 {section} 节第 {number} 条证据等级不是 A/B/C：{fields["证据等级"]!r}')
    score, tier = ratio(cost_tags)
    dispute = _dispute(fields['备注'], DISPUTE_SENTENCES.get(title, 1))
    return {'section': section, 'section_title': section_title, 'number': number, 'title': title,
            'cost_tags': cost_tags, 'cost_score': score, 'ratio': tier,
            'lens': LENS.get(cost_tags.get('口径', ''), cost_tags.get('口径', '')),
            'fields': fields, 'grade': grade,
            # index.html: 待核实 or TODO in 来源, 收益, 备注 or 成本.
            'todo': bool(re.search(r'待核实|TODO', fields['来源'] + fields['收益'] + fields['备注'] + fields['成本'])),
            'disputed': dispute is not None, 'dispute': dispute, 'region': _region(section, title)}


def _intro(text: str) -> list[str]:
    """Paragraphs between the section heading and its first entry."""
    body = SECTION_RE.split(text, maxsplit=1)[-1]
    body = body.split('\n### ', 1)[0] if '\n### ' in body else body
    lines = [ln.rstrip() for ln in body.splitlines()[1:]]
    paras: list[str] = []
    cur: list[str] = []
    for line in lines:
        if not line.strip() or NAV_RE.match(line.strip()):
            if cur:
                paras.append('\n'.join(cur))
                cur = []
            continue
        cur.append(line)
    if cur:
        paras.append('\n'.join(cur))
    return paras


def _readme_section(readme: str, heading: str) -> str:
    found = re.search(rf'^## {re.escape(heading)}[^\n]*\n(.*?)(?=^## )', readme, re.M | re.S)
    if not found:
        raise ValueError(f'README 里没有「{heading}」一节')
    return found.group(1).strip()


def _guide(readme: str) -> dict:
    questions = [{'section': int(m.group(2)), 'question': m.group(1).strip()}
                 for m in re.finditer(r'^\|\s*(.+?)\s*\|\s*\[\d+\.[^\]]*\]\(book/(\d{2})-[^)]*\)\s*\|$',
                                      _readme_section(readme, '这本书想回答的问题'), re.M)]
    glossary = []
    for m in re.finditer(r'^\|\s*(.+?)\s*\|\s*(.+?)\s*\|$', _readme_section(readme, '读懂数字'), re.M):
        if m.group(1) in ('术语', '---') or set(m.group(1)) <= {'-', ' '}:
            continue
        glossary.append({'term': m.group(1), 'meaning': m.group(2)})
    return {'questions': questions, 'glossary': glossary,
            'resources': _readme_section(readme, '四种资源'),
            'grades': _readme_section(readme, '证据分级'),
            'ratio': _readme_section(readme, '性价比档')}


def _drop_paragraphs(section: int, text: str) -> str:
    """Remove the reviewed intro paragraph; refuse if it is not there."""
    if section not in EXCLUDED_PARAGRAPHS:
        return text
    opening = EXCLUDED_PARAGRAPHS[section][0]
    lines = text.split('\n')
    first_entry = next((i for i, ln in enumerate(lines) if ln.startswith('### ')), len(lines))
    hits = [i for i in range(first_entry) if lines[i].startswith(opening)]
    if len(hits) != 1:
        raise ValueError(f'第 {section} 节导读里找不到唯一一段以「{opening}」开头的段落')
    return '\n'.join(lines[:hits[0]] + lines[hits[0] + 1:])


def _member(archive: zipfile.ZipFile, suffix: str) -> str | None:
    return next((n for n in archive.namelist() if n.endswith(suffix)), None)


def _check_trace(source: str, text: str, excluded_titles: dict[tuple[int, int], str]) -> list[str]:
    """Divination words, whole-section references to an excluded entry's
    section, and quoted excluded titles: each must be reviewed."""
    found = [f'{source} 含「{w}」' for w in DIVINATION_WORDS if w in text]
    for m in SECTION_ONLY_RE.finditer(text):
        sec = int(m.group(1))
        if any(s == sec for s, _ in EXCLUDED) and (source, sec) not in REVIEWED_SECTION_REFS:
            found.append(f'{source} 引用整个第 {sec} 节（含被排除条目）')
    for quoted in QUOTE_RE.findall(text):
        for key, title in excluded_titles.items():
            if quoted in title or title in quoted:
                found.append(f'{source} 引用了被排除条目 {key} 的标题「{quoted}」')
    return found


def build(zip_path: Path, check_reviews: bool = True) -> dict:
    """``check_reviews=False`` only for synthetic snapshots in tests, which
    cannot hold the reviewed titles of the real book."""
    with zipfile.ZipFile(zip_path) as archive:
        commit = archive.comment.decode('ascii', 'replace').strip()
        if commit != COMMIT:
            raise ValueError(f'ZIP 提交是 {commit or "（无注释）"}，不是固定的 {COMMIT}')
        files: dict[str, str] = {}
        books: dict[int, str] = {}
        for name in sorted(n for n in archive.namelist() if re.search(r'/book/\d{2}-[^/]+\.md$', n)):
            raw = archive.read(name)
            base = name.rsplit('/', 1)[-1]
            files['book/' + base] = hashlib.sha256(raw).hexdigest()
            books[int(base[:2])] = _drop_paragraphs(int(base[:2]), raw.decode('utf-8').replace('\r\n', '\n'))
        docs: dict[str, str] = {}
        for name in sorted(n for n in archive.namelist() if re.search(r'/docs/[^/]+\.md$', n)):
            base = name.rsplit('/', 1)[-1]
            if base in NOT_ARTICLES:
                continue
            if base not in ARTICLES:
                raise ValueError(f'快照里有未审定的长文 {base}：先在 ARTICLES 里定下编号和地区')
            raw = archive.read(name)
            files['docs/' + base] = hashlib.sha256(raw).hexdigest()
            docs[base] = raw.decode('utf-8').replace('\r\n', '\n')
        missing = set(ARTICLES) - set(docs)
        if missing:
            raise ValueError(f'快照里没有长文 {sorted(missing)}')
        readme_name = _member(archive, '/README.md')
        if readme_name is None:
            raise ValueError('快照里没有 README.md')
        readme_raw = archive.read(readme_name)
        files['README.md'] = hashlib.sha256(readme_raw).hexdigest()
        readme = readme_raw.decode('utf-8').replace('\r\n', '\n')
        # The MIT notice must travel with the ported code (index.html,
        # tools/, skills/): ship it verbatim.
        code_license_name = _member(archive, '/LICENSE-CODE')
        if code_license_name is None:
            raise ValueError('快照里没有 LICENSE-CODE（代码部分的 MIT 许可）')
        code_notice = archive.read(code_license_name).decode('utf-8').replace('\r\n', '\n').strip()
        if not code_notice.startswith('MIT License'):
            raise ValueError('LICENSE-CODE 不再是 MIT 许可：先复核移植代码能否继续使用')

    sections: list[dict] = []
    entries: list[dict] = []
    excluded_titles: dict[tuple[int, int], str] = {}
    for sec, text in sorted(books.items()):
        head = SECTION_RE.search(text)
        sec_title = head.group(2).strip() if head else ''
        sections.append({'section': sec, 'title': sec_title, 'intro': _intro(text)})
        for block in re.split(r'\n(?=### )', text):
            if not block.startswith('### '):
                continue
            entry = _entry(sec, sec_title, block)
            key = (entry['section'], entry['number'])
            if key in EXCLUDED:
                fragment = EXCLUDED[key][0]
                if fragment not in entry['title']:
                    raise ValueError(f'排除清单 {key} 现在是「{entry["title"]}」，不含「{fragment}」：编号可能已变化')
                excluded_titles[key] = entry['title']
                continue
            entries.append(entry)
    if set(excluded_titles) != set(EXCLUDED):
        raise ValueError('排除清单里有条目在快照中找不到，编号可能已变化')
    titles = {e['title'] for e in entries}
    stale = sorted(set(REGION) - titles) + sorted(set(DISPUTE_SENTENCES) - titles)
    if stale and check_reviews:
        raise ValueError('审定数据里的标题在快照中找不到，须重审：' + json.dumps(stale, ensure_ascii=False))
    _attach_refs(books, docs, sections, entries)
    articles = [{'id': ARTICLES[base][0], 'path': 'docs/' + base, 'title': _doc_title(base, text),
                 'region': ARTICLES[base][1], 'text': text} for base, text in sorted(docs.items())]
    _attach_article_refs(books, docs, articles)
    guide = _guide(readme)
    problems = _check_trace('README', json.dumps(guide, ensure_ascii=False), excluded_titles)
    for e in entries:
        problems += _check_trace(e['title'], e['title'] + '\n' + '\n'.join(e['fields'].values()), excluded_titles)
    for s in sections:
        problems += _check_trace(f'节首:{s["section"]}', '\n'.join(str(p) for p in s['intro']), excluded_titles)
    for a in articles:
        problems += _check_trace(f'长文:{a["id"]}', a['text'], excluded_titles)
    if problems:
        raise ValueError('须先人工审定：' + json.dumps(problems, ensure_ascii=False))
    return {
        'schema_version': '2.0',
        'title': '高性价比人生指南',
        'purpose': '现实参考资料库：除按产品范围略去的 3 条外完整收录。术数回答之后单独成段，'
                   '或回答人生决策问题；不参与择日、配色等术数排序。',
        'source': {'repo': REPO, 'commit': COMMIT, 'snapshot_date': SNAPSHOT_DATE,
                   'license': LICENSE['text'], 'license_detail': {**LICENSE, 'code_notice': code_notice},
                   'files': files},
        'coverage': {'entries': len(entries), 'excluded': len(EXCLUDED), 'sections': len(sections),
                     'articles': len(articles)},
        'region_policy': {'universal_sections': sorted(UNIVERSAL_SECTIONS),
                          'abroad_sections': sorted(ABROAD_SECTIONS),
                          'default': '中国大陆', 'overrides': len(REGION)},
        'guide': guide,
        'sections': sections,
        'articles': articles,
        'entries': entries,
    }


def _doc_title(base: str, text: str) -> str:
    head = re.search(r'^#\s+(.+)$', text, re.M)
    if not head:
        raise ValueError(f'长文 {base} 没有一级标题')
    return head.group(1).strip()


def _attach_refs(books: dict[int, str], docs: dict[str, str], sections: list[dict], entries: list[dict]) -> None:
    """Each entry and intro gets the entries it refers to, resolved the book's way."""
    found = scan(books, docs)
    if found.problems:
        raise ValueError('交叉引用有问题：' + json.dumps(found.problems[:20], ensure_ascii=False))
    by_key = {(e['section'], e['number']): e for e in entries}
    by_sec = {s['section']: s for s in sections}
    for e in entries:
        e['refs'] = []
    for s in sections:
        s['refs'] = []
    for ref in found.refs:
        if ref.unit == 'doc':
            continue
        source = by_key.get((ref.section, ref.entry)) if ref.unit == 'book' else by_sec[ref.section]
        if source is None:                        # a reference made by an excluded entry
            continue
        if ref.target in EXCLUDED:
            name = source['title'] if ref.unit == 'book' else f'节首:{ref.section}'
            if (name, ref.target) not in REVIEWED_CROSS_REFS:
                raise ValueError(f'{name} 引用了被排除条目 {ref.target}，须先人工审定')
            continue
        target = [ref.target[0], ref.target[1]]
        if target not in source['refs']:
            source['refs'].append(target)


def _attach_article_refs(books: dict[int, str], docs: dict[str, str], articles: list[dict]) -> None:
    by_path = {a['path']: a for a in articles}
    for base, text in docs.items():
        article = by_path['docs/' + base]
        article['refs'] = []
        for ref in scan(books, {base: text}).refs:
            if ref.unit != 'doc':
                continue
            if ref.target in EXCLUDED:
                if (f'长文:{article["id"]}', ref.target) not in REVIEWED_CROSS_REFS:
                    raise ValueError(f'长文 {base} 引用了被排除条目 {ref.target}，须先人工审定')
                continue
            if list(ref.target) not in article['refs']:
                article['refs'].append(list(ref.target))


def main(argv: list[str] | None = None) -> int:
    ensure_utf8_stdio()
    parser = argparse.ArgumentParser(
        description='把《高性价比人生指南》固定快照导入 assets/life_guide.json；维护工具，不进运行包',
        epilog='Writes assets/life_guide.json. Top-level JSON keys: schema_version title purpose '
               'source coverage region_policy guide sections articles entries')
    parser.add_argument('--zip', type=Path, required=True, help='GitHub codeload ZIP，注释须为固定提交')
    args = parser.parse_args(argv)
    try:
        data = build(args.zip)
    except (OSError, ValueError, zipfile.BadZipFile) as exc:
        print(f'导入失败：{exc}', file=sys.stderr)
        return 1
    OUTPUT.write_text(json.dumps(data, ensure_ascii=False, indent=1) + '\n', encoding='utf-8', newline='\n')
    c = data['coverage']
    print(f'{OUTPUT.relative_to(ROOT)}：{c["entries"]} 条（排除 {c["excluded"]} 条），{c["sections"]} 节，'
          f'长文 {c["articles"]} 篇，提交 {COMMIT[:12]}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
